import marshal, os, base64, zlib
from uncompyle6.main import decompile as dec
from sys import stdout
from var_animate import *
banner = banner('MarshEnc', 'Dst_207', '0.1')
color = color()
input = animinput()
me = color.show('red')
bi = color.show('blue')
pu = color.show('white')
cy = color.show('cyan')
i = color.show('green')
os.system('clear')
alert = animvar()
print banner
print ('{}Team{}: {}BlackCoderCrush & DevSec45').format(cy, me, pu)
print ('{}[{}1{}] Enc Marshal {}[ {}Berlapis {}]').format(pu, i, pu, bi, pu, bi)
print ('{}[{}2{}] Enc Marshal').format(pu, i, pu)
print ('{}[{}3{}] Dec Marshal ').format(pu, i, pu)
ask = input.ask('Pilih')
if ask == '1' or ask == '01':
    print ('   {}[ {}Compile Marshal Berlapis {}]').format(bi, pu, bi)
    file = input.ask('File')
    os.system('cp ' + file + ' tes.py')
    jml = int(input.ask('JumlahEnc'))
    for i in range(jml):
        cod = open('tes.py', 'r').read()
        pile2 = compile(cod, '<DestaGans>', 'x = ')
        data = marshal.dumps(pile2)
        f = open('tes.py', 'w')
        f.write('# Compiled Berlapis by Dst_207\n')
        f.write('# DESTA GANS\n')
        f.write('# Team: DevSec45&BlackCoderCrush\n')
        f.write('import marshal\n')
        f.write('x = (marshal.loads(' + repr(data) + '))')
        f.close()

    out = input.ask('Output')
    os.system('touch ' + out)
    os.system('mv tes.py ' + out)
    print alert.true('JumlahEnc: ' + str(jml))
    print alert.true('PATH: ' + out)
elif ask == '2' or ask == '02':
    print ('   {}[ {}compile Marshal{}]').format(bi, pu, bi)
    file = input.ask('File')
    os.system('cp ' + file + ' tes.py')
    cod = open('tes.py', 'r').read()
    pile2 = compile(cod, '<DestaGans>', 'x = ')
    data = marshal.dumps(pile2)
    f = open('tes.py', 'w')
    f.write('# Compiled by Dst_207\n')
    f.write('# DESTA GANS\n')
    f.wrtie('# Team: DevSec45&BlackCoderCrush\n')
    f.write('import marshal\n')
    f.write('x = (marshal.loads(' + repr(data) + '))')
    f.close()
    out = input.ask('Output')
    os.system('touch ' + out)
    os.system('mv tes.py ' + out)
elif ask == '3' or ask == '03':
    print ('   {}[ {}Decompile Marshal{}]').format(bi, pu, bi)
    file = input.ask('File')
    os.system('touch tesdec.py')
    byte = open(file, 'r').read()
    byte = byte.replace('import marshal', '')
    byte = byte.replace('x = (', '')
    byte = byte.replace('))', ')')
    os.system(('python2 -c "\nfrom uncompyle6.main import decompile as dec\nimport marshal\nfrom sys import stdout\ndec(2.7,{},stdout)" > tesdec.py').format(byte))
    out = input.ask('Output')
    os.system('mv tesdec.py ' + out)
    print alert.true('PATH: ' + out)
else:
    time.sleep(1)
    print alert.false('Pilihan Anda Salah')
    time.sleep(1)
    os.system('python2 marsh.py')
